
### 创建字典
post http://localhost:9898/api/dictionaries/generateDictionary
Content-Type: application/json

{   
   "code":2,
   "value":"Vue",
   "description":"Vue 框架"
}

### 更新字典
post http://localhost:9898/api/dictionaries/generateDictionary
Content-Type: application/json

{   "id":1,
   "code":2,
   "value":"React",
   "description":"React 框架"
}

### 删除字典
post http://localhost:9898/api/dictionaries/deleteDictionary
Content-Type: application/json

{ 
    "ids":[3]  
}

### 查询字典信息
get http://localhost:9898/api/dictionaries/getDictionaryInfo?id=1

### 查询字典列表
post http://localhost:9898/api/dictionaries/getDictionaryList
Content-Type: application/json

{   
    "pageNum":1,
    "pageSize":10,
    "code":""
}

### 创建项目信息
post http://localhost:9898/api/project/generateProject 
Content-Type: application/json

{

    "project_name":"测试项目1",
    "description":"测试项目1",
    "sql_host":"127.0.0.1",
    "sql_prot":"3306",
    "sql_basename":"csxm",
    "sql_user":"root",
    "sql_password":"123456",
    "frame_id":2
}

### 更新项目信息
post http://localhost:10101/generateProject
Content-Type: application/json

{   "id":8,
    "sql_user":"roots1112222"
}

### 删除项目信息

post http://localhost:9898/api/project/deleteProject
Content-Type: application/json

{  
    "ids":[1]
}

### 查询项目列表
post http://localhost:9898/api/project/getProjectList
Content-Type: application/json

{
    "pageNum":1,
    "pageSize":10,
    "project_name":"",
    "sql_host":""
}

### 获取项目信息
get http://localhost:9898/api/project/getProjectInfo?id=1




############################################ 


### 创建表
post http://localhost:9898/api/form/generateForm
Content-Type: application/json

{

    "project_id":2,
    "form_comment":"这是一张用户表",
    "form_name":"user"
}

### 更新表
post http://localhost:9898/api/form/generateForm
Content-Type: application/json

{   "id":1,
    "form_name":"user"
}

### 删除表

post http://localhost:9898/api/form/deleteForm
Content-Type: application/json

{  
    "ids":[2]
}

### 查询表列表
post http://localhost:9898/api/form/getFormList
Content-Type: application/json

{
    "pageNum":1,
    "pageSize":10,
    "project_id":2
   
}

### 获取表信息
get http://localhost:9898/api/form/getFormInfo?id=3
