### 创建字段
### "default_value":"0"
post http://localhost:9898/api/field/generateField
Content-Type: application/json

{
  "form_id": 1,
  "field_type": "[]Role",
  "field_name": "[]Role",
  "auto_increment": false,
  "is_primary_key":false,
  "is_val_null": "-",
  "is_query": true,
  "many":"business_user_role",
  "is_pointer": false,
  "is_add": false,
  "is_null":false,
  "field_size":0,
  "index_name":"",
  "is_unique":false
}

### 更新字段
post http://localhost:9898/api/field/generateField
Content-Type: application/json

{
  "id":18,
   "field_type": "[]Role",
  "field_name": "Role"
}