### 创建表(没问题)
post http://localhost:9898/api/form/generateForm
Content-Type: application/json

{
    "project_id": 1,
    "form_comment": "这是一张日志表",
    "form_name": "Logger"
}


### 更新表
post http://localhost:9898/api/form/generateForm
Content-Type: application/json

{   "id":2,
    "before_creates":"{\"function\":\"BeforeCreate\",\"description\":\"Sets the ID of the role. If the role name is 'admin', the ID is set to a specific value.\",\"steps\":[{\"action\":[{\"operation\":\"GenerateID\",\"result\":\"r.ID\"}]},{\"condition\":\"r.RoleName == 'admin'\",\"action\":[{\"operation\":\"SetID\",\"value\":1887415157}]}]}",
    "before_deletes":"{\"function\":\"BeforeDelete\",\"description\":\"Prevents deletion of the role with ID 1887415157 (admin).\",\"steps\":[{\"condition\":\"r.ID == 1887415157\",\"action\":[{\"operation\":\"ReturnError\",\"errorMessage\":\"admin user not allowed to delete\"}]}]}"
}

### 删除表

post http://localhost:9898/api/form/deleteForm
Content-Type: application/json

{  
    "ids":[2]
}

### 查询表列表
post http://localhost:9898/api/form/getFormList
Content-Type: application/json

{
    "pageNum":1,
    "pageSize":10,
    "project_id":2
   
}

### 获取表信息
get http://localhost:9898/api/form/getFormInfo?id=3
