### 创建msgCode 
post http://localhost:9898/api/msgCode/generateMsgCode
Content-Type: application/json

{   
   "key":"NoPermission",
   "code":401,
   "msg":"No permission"
}
###更新msgCode

post http://localhost:9898/api/msgCode/generateMsgCode
Content-Type: application/json

{   
    "id":6,
    "key":"Unauthorized",
   "code":401,
   "msg":"Unauthorized"
}
### 获取msgCode列表

post http://localhost:9898/api/msgCode/getMsgCodeList
Content-Type: application/json

{   
    "msg_key":"u",
    "code":"401",
   "pageNum":1,
    "pageSize":10
}
